### ISSUE TITLE
Issues at lower zoom

### ISSUE THREAD

**Issue by musicformellons** [pka/t-rex#39]
I noticed following behavior and do not know 'what is going on':
When I worked with 50K points and generated tiles, the tiles for the lower zooms were ready in an instant (couple of seconds). Now I have 180K points and before it generates zoom 0 it scans features for 3 minutes or so.

Furthermore the points do not appear in the lower zoom, also not when cached (and after refreshing my browser cache of course). 
I would expect when zoom 0 is cached that you do not see the request, but the request shows and I get following errors at lower zooms:
```
2017-07-02 12:17:42.913 INFO GET /customlayer/3/3/2.pbf
2017-07-02 12:17:48.136 INFO GET /customlayer/3/3/3.pbf
2017-07-02 12:17:49.160 INFO GET /customlayer/3/5/2.pbf
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
2017-07-02 12:18:09.522 INFO GET /customlayer/3/5/3.pbf
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859
2017-07-02 12:18:10.105 INFO GET /customlayer/2/2/1.pbf
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859
2017-07-02 12:18:12.322 INFO GET /customlayer/2/1/1.pbf
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859
2017-07-02 12:18:12.950 INFO GET /customlayer/2/2/0.pbf
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859
2017-07-02 12:18:19.238 INFO GET /customlayer/2/1/0.pbf
2017-07-02 12:18:31.114 INFO GET /customlayer/2/3/1.pbf
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859
2017-07-02 12:18:42.357 INFO GET /customlayer/2/3/0.pbf
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859
2017-07-02 12:18:42.971 INFO GET /customlayer/1/1/0.pbf
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859
2017-07-02 12:18:49.252 INFO GET /customlayer/1/0/0.pbf
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859
2017-07-02 12:19:01.155 INFO GET /customlayer/1/0/1.pbf
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859
2017-07-02 12:19:12.382 INFO GET /customlayer/1/1/1.pbf
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859
2017-07-02 12:19:12.990 INFO GET /customlayer/0/0/0.pbf
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859
2017-07-02 12:19:19.276 INFO GET /customlayer/0/0/0.pbf
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859
2017-07-02 12:19:31.178 INFO GET /customlayer/0/0/0.pbf
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: GetTimeout(None)', /checkout/src/libcore/result.rs:859

```

Any suggestions are highly appreciated.

**Comment by musicformellons** [comment]
Mmmh, the cachefolder was an invalid path. After correcting that the points do show at lower zooms. It is still taking a long time to generate the tiles of lower zooms, but probably that is simply because of having more points I suppose.
