### ISSUE TITLE
Enable SSL mode for PostgreSQL connections

### ISSUE THREAD

**Issue by homme** [pka/t-rex#51]
I don't seem to be able to enable SSL in database connections. I'm running the following using `t_rex` **0.7.7-dev**:

```
./t_rex genconfig --clip true --simplify true --dbconn 'postgres://***:***@***:***/***?sslmode=require'
```
And get the following output:
```
2017-07-26 13:17:28.530 ERROR Error opening a connection: Error reported by Postgres: FATAL: no pg_hba.conf entry for host "***", user "***", database "***", SSL off
[ logs repeated ]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InitializationError(Some("Error opening a connection: Error reported by Postgres: FATAL: no pg_hba.conf entry for host \"***\", user \"***\", database \"***\", SSL off"))', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:71
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:371
             at /checkout/src/libstd/panicking.rs:549
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   4: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   5: core::panicking::panic_fmt
             at /checkout/src/libstd/panicking.rs:471
   6: core::result::unwrap_failed
   7: t_rex::datasource::postgis::PostgisInput::connected
   8: t_rex::webserver::server::service_from_args
   9: t_rex::webserver::server::gen_config
  10: t_rex::main
  11: main
  12: __libc_start_main
  13: <unknown>
1
```

Is there something I'm missing in order to specify a SSL connection?

**Comment by pka** [comment]
Added in 0.7.8
